export const SERVICESLIST = {
  name: "Services",
  cards: [
    {
      id: 1,
      heading: "Search engine",
      subheading: "optimization",
      bgColor: "bg-grey",
      headingColor: "bg-green",
      src: "/images/services-01.png",
      btnTextColor: "text-black",
      svgClass: "bg-black text-green",
    },
    {
      id: 2,
      heading: "Pay-per-click",
      subheading: "advertising",
      bgColor: "bg-green",
      headingColor: "bg-white",
      src: "/images/services-02.png",
      btnTextColor: "text-black",
      svgClass: "bg-black text-green",
    },
    {
      id: 3,
      heading: "Social Media",
      subheading: "Marketing",
      bgColor: "bg-black",
      headingColor: "bg-white",
      src: "/images/services-03.png",
      btnTextColor: "text-white",
      svgClass: "bg-white text-black",
    },
    {
      id: 4,
      heading: "Email",
      subheading: "Marketing",
      bgColor: "bg-grey",
      headingColor: "bg-green",
      src: "/images/services-04.png",
      btnTextColor: "text-black",
      svgClass: "bg-black text-green",
    },
    {
      id: 5,
      heading: "Content",
      subheading: "Creation",
      bgColor: "bg-green",
      headingColor: "bg-white",
      src: "/images/services-05.png",
      btnTextColor: "text-black",
      svgClass: "bg-black text-green",
    },
    {
      id: 6,
      heading: "Analytics and ",
      subheading: "Tracking",
      bgColor: "bg-black",
      headingColor: "bg-green",
      src: "/images/services-06.png",
      btnTextColor: "text-white",
      svgClass: "bg-white text-black",
    },
  ],
};
